%Doctor.Config{
  exception_moduledoc_required: true,
  failed: false,
  ignore_modules: [
    ~r(^Remedy.Gateway.Dispatch),
    ~r(^Remedy.Gateway.Events),
    ~r(^Remedy.Gun),
    ~r(^Remedy.Helpers),
    ~r(^Mix.Tasks),
    Remedy.API.Rest,
    Remedy.API.RestRequest,
    Remedy.API.RestResponse,
    Remedy.Application,
    Remedy.Cache.DiscordApp,
    Remedy.Cache.DiscordBot,
    Remedy.Cache.Repo,
    Remedy.CacheSupervisor,
    Remedy.Gateway.EventBroadcaster,
    Remedy.Gateway.EventBuffer,
    Remedy.Gateway.Pacemaker,
    Remedy.Gateway.Payload,
    Remedy.Gateway.Session,
    Remedy.Gateway.Intents,
    Remedy.Gateway.SessionSupervisor,
    Remedy.GatewayATC,
    Remedy.OpcodeHelpers,
    Remedy.TimeHelpers,
    Remedy.ModelHelpers
  ],
  ignore_paths: [],
  min_module_doc_coverage: 80,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 50,
  min_overall_spec_coverage: 0,
  moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: true,
  umbrella: false
}
